/**
 * This file is auto-generated by the Supabase CLI.
 * Run: npm run db:gen-types
 * 
 * DO NOT EDIT MANUALLY
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      status_types: {
        Row: {
          id: string
          label: string
          description: string | null
          color: string | null
          sort_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          label: string
          description?: string | null
          color?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          label?: string
          description?: string | null
          color?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
      }
      students: {
        Row: {
          id: string
          student_code: string | null
          first_name: string
          surname: string
          chinese_name: string | null
          gender: string | null
          date_of_birth: string | null
          nationality: string | null
          passport_number: string | null
          email: string | null
          phone: string | null
          address: string | null
          present_school: string | null
          entry_year: string | null
          status: string | null
          notes: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          student_code?: string | null
          first_name: string
          surname: string
          chinese_name?: string | null
          gender?: string | null
          date_of_birth?: string | null
          nationality?: string | null
          passport_number?: string | null
          email?: string | null
          phone?: string | null
          address?: string | null
          present_school?: string | null
          entry_year?: string | null
          status?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
        Update: {
          id?: string
          student_code?: string | null
          first_name?: string
          surname?: string
          chinese_name?: string | null
          gender?: string | null
          date_of_birth?: string | null
          nationality?: string | null
          passport_number?: string | null
          email?: string | null
          phone?: string | null
          address?: string | null
          present_school?: string | null
          entry_year?: string | null
          status?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
      }
      schools: {
        Row: {
          id: string
          name: string
          type: string
          country: string | null
          city: string | null
          address: string | null
          website: string | null
          notes: string | null
          status: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          name: string
          type: string
          country?: string | null
          city?: string | null
          address?: string | null
          website?: string | null
          notes?: string | null
          status?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          type?: string
          country?: string | null
          city?: string | null
          address?: string | null
          website?: string | null
          notes?: string | null
          status?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
      }
      events: {
        Row: {
          id: string
          name: string
          type: string
          start_date: string | null
          end_date: string | null
          location: string | null
          description: string | null
          status: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          name: string
          type: string
          start_date?: string | null
          end_date?: string | null
          location?: string | null
          description?: string | null
          status?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          type?: string
          start_date?: string | null
          end_date?: string | null
          location?: string | null
          description?: string | null
          status?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
      }
      student_contacts: {
        Row: {
          id: string
          student_id: string
          relation: string
          first_name: string
          surname: string
          title: string | null
          gender: string | null
          phone: string | null
          mobile: string | null
          email: string | null
          occupation: string | null
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          student_id: string
          relation: string
          first_name: string
          surname: string
          title?: string | null
          gender?: string | null
          phone?: string | null
          mobile?: string | null
          email?: string | null
          occupation?: string | null
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          relation?: string
          first_name?: string
          surname?: string
          title?: string | null
          gender?: string | null
          phone?: string | null
          mobile?: string | null
          email?: string | null
          occupation?: string | null
          is_primary?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Convenience type helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
